### PR TITLE
Upgrade get-pixels dependency to 3.3.0

### PR DESCRIPTION
**Pull request by martinkadlec0**

### CODE REVIEW

**Comment by twolfson** [comment]
Awesome, thanks. I will land this by the end of the weekend (probably tonight).

As a heads up, your `git` author seems to be improperly configured (i.e. it's not linking to your GitHub account). See the `?` on the commit:

https://github.com/twolfson/pixelsmith/pull/9/commits/12fc155c5febfc045af7c76bd4d6df3b616b29bc

**Comment by martinkadlec0** [comment]
Thanks! Looking forward for the publishing :)

**Comment by twolfson** [comment]
This has been merged/released in `2.1.1` (patch release so `spritesmith` will pick it up seamlessly)

**Comment by twolfson** [comment]
Thanks again for the PR =)

**Pull request merged**
